export enum IocTokens {
  CRYPTO_SERVICE = 'CRYPTO_SERVICE',
  DATA_SOURCE = 'DATA_SOURCE',
  LESSON_REPOSITORY = 'LESSON_REPOSITORY',
  USER_REPOSITORY = 'USER_REPOSITORY',
  COURSE_REPOSITORY = 'COURSE_REPOSITORY',
}
