version: '3.8'
name: alto-pg
services:
  db:
    image: postgres:15.2-alpine
    restart: always
    build: /database/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081

  grafana:
    container_name: alto_grafana
    image: grafana/grafana:7.5.6
    restart: always
    ports:
      - 3033:3000
    volumes:
       - ./monitoring/grafana/grafana.ini:/etc/grafana/grafana.ini

volumes:
  db:
    driver: local