version: '3.8'
services:

  db:
    image: postgres:15.2-alpine
    restart: always
    build: /database/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db:
    driver: local