version: '3.8'
name: alto-studio
services:
  alto-postgres:
    image: postgres:15.2-alpine
    restart: always
    build: ./database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5438:5432'
  alto-mongodb:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - alto-mongodb:/data/db

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8282:8080

#  grafana:
#    container_name: alto_grafana
#    image: grafana/grafana:7.5.6
#    restart: always
#    ports:
#      - 3033:3000
#    volumes:
#       - monitoring/grafana/grafana.ini:/etc/grafana/grafana.ini

volumes:
  alto-postgres:
    driver: local
  alto-mongodb:
